# Site settings
title: OpenIntents
email: support@openintents.org
description: > 
  OpenIntents is a community to show case the use of the Android intent system.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://www.openintents.org" # the base hostname & protocol for your site
twitter_username: openintents
github_username:  openintents

# Build settings
markdown: kramdown
highlighter: rouge

collections:
  intent_specs:
    output: true